// NAME MUST BE THE SAME USED IN ./l2d.json
// IF CHARACTER HAVE BEEN ADDED AFTER OVERZONE (18th may 2023) YOU MUST SAY IT IN l2d.json WITH SPINE VERSION 4.1
// CHECK BLANC, NOIR, OR RUPEE SKIN FOR EXAMPLE
export const RELEASED_UNITS = [
  '2B',
  '2B Metamorphic Damage',
  '2B YoRHa Uniform 1',
  '777',
  '9S',
  'A2',
  'A2 Metamorphic Damage',
  'A2 YoRHa Uniform Prototype',
  'ACPU FREEZE',
  'Ade',
  'Admi',
  'Aegis the Diver',
  'Aki Hayakawa',
  'Alice',
  'Alice: Wonderland Bunny',
  'Alice Sweet Home',
  'Alone Survivor',
  'Anachiro | Cinderella',
  'Anne: Miracle Fairy',
  'Andersen',
  'Andersen Soaked',
  'Anis',
  'Anis: Sparkling Summer',
  'Anchor',
  'Anchor the Diver',
  'Angelina',
  'Aria',
  'Bay',
  'Beatrice',
  'Belorta',
  'Biscuit',
  'Black Ark Ranger',
  'Blanc',
  'Blanc White Rabbit',
  'Blue Water Island',
  'Beauty Full Shot',
  'Bolt',
  'Bolt Junior',
  'Booboo',
  'BOOM\'s DAY',
  'Boss: Mother Whale',
  'Boss: Harvester',
  'Boss: Chatterbox',
  'Boss: Blacksmith',
  'Boss: Storm Bringer',
  'Boss: Gatekeeper Blue',
  'Boss: Gatekeeper Green',
  'Boss: Gatekeeper Red',
  'Boss: Land Eater',
  'Boss: Material H',
  'Boss: Nihilister',
  'Boss: Alteisen',
  'Boss: Grave Digger',
  'Boss: Modernia',
  'Boss: Modernia Intro',
  'Bow Wow Paradise',
  'Brand New Year',
  'Brid',
  'Brid Model Worker',
  'Brid Black Moon',
  'Bridget',
  'Burningum',
  'Cecil',
  'Centi',
  'Centi Supreme Holiday',
  'Cherry Blossom',
  'Chime',
  'Clay',
  'Claymore',
  'Cocoa',
  'Collection Robot',
  'Commander (GODDESS)',
  'Crow',
  'Crown',
  'Crown Naked King',
  'D',
  'D.ARK HERO',
  'D: Killer Wife',
  'D Outsider',
  'Dazzling Cupid: Naga',
  'Dazzling Cupid: Tia',
  'Delta',
  'Denji',
  'Denji Chainsaw Man',
  'Diesel',
  'Diesel Black Sunday',
  'Diesel Strawberry Flower',
  'Diesel Midnight Strawberry',
  'Dirty Backyard',
  'Doban',
  'Dolla',
  'Dolla Dark Rose',
  'Dorothy',
  'Dorothy Nostalgia',
  'Drake',
  'Drake Maid For Villain',
  'Drake Villain Racer',
  'Drilley',
  'E.H.',
  'Elegg',
  'Ember',
  'Emma',
  'Emma Color Me Red',
  'Emma Office Therapy',
  'Enikk',
  'Ein',
  'Einkk',
  'Epinel',
  'Espinel',
  'Ether',
  'Eunhwa',
  'Exia',
  'Exia Joy to the Nerds',
  'Exia Gamer',
  'Faceless Man',
  'Faceless NPC 1',
  'Faceless NPC 2',
  'Faceless NPC 3',
  'Faceless NPC 4',
  'Faceless NPC 5',
  'Faceless NPC 6',
  'Faceless NPC 7',
  'Faceless NPC 8',
  'Faceless NPC 9',
  'Faceless Woman',
  'Favorite: Diesel',
  'Favorite: Laplace',
  'Favorite: Frima',
  'Favorite: Exia',
  'Flora',
  'Folkwang',
  'Folkwang Moist Bunny',
  'Fragile',
  'Freesia',
  'Frima',
  'Frima Sea of Sloth',
  'Ghost: Lumi',
  'Ghost: Lena',
  'Ghost: Lua',
  'Golden Coin Rush',
  'Golden Ship',
  'Grave',
  'Guillotine',
  'Guillotine Dark Tracer',
  'Guilty',
  'Guilty Wave of Disbelief',
  'Hammering',
  'Harran',
  'Harran Banquet Witch',
  'Helm',
  'Helm Chandelier',
  'Helm: Aquamarine',
  'High Tech Toy',
  'Himeno',
  'Hologram',
  'iDoll Flower',
  'iDoll Ocean',
  'iDoll Sun',
  'Indivilia',
  'Ingrid',
  'Isabel',
  'Jackal',
  'Johan',
  'Joseph',
  'Julia',
  'Julia Mild Nocturne',
  'K',
  'Katie',
  'Kill The Lord',
  'Kilo',
  'Laplace',
  'Last Kingdom',
  'Leona',
  'Liberalio',
  'Liberty',
  'License to Kill',
  'Liliweiss',
  'Lion Heart',
  'Liter',
  'Liter Guardfish',
  'Liter Cute Sunflower',
  'Liveryn',
  'Lucilla',
  'Ludmilla',
  'Ludmilla: Winter Owner',
  'Lumi',
  'Maid in Valentine',
  'Maiden',
  'Maiden Covert Nurse',
  'Maiden Under the Sun',
  'Makima',
  'Makima Coat Off',
  'Mana',
  'Marciana',
  'Marian',
  'Mary',
  'Mary Medical Rabbit',
  'Mary: Bay Goddess',
  'Mass Produced Red',
  'Mass Produced Blue',
  'Mass Produced Orange',
  'Mass Produced Green',
  'Mass Produced Purple',
  'Mass Produced White',
  'Mass Produced Melee',
  'Mass Produced Melee 2',
  'Mast',
  'Mast A Pirate\'s Heart',
  'Mast the Diver',
  'Mast_old',
  'Max',
  'Maxine',
  'Maxwell',
  'Maxwell Mechanic White',
  'Mica',
  'Mica: Snow Buddy',
  'Mihara',
  'Milk',
  'Milk Extreme Fighter',
  'Miranda',
  'Miracle Snow',
  'Modernia',
  'Modernia First Affection',
  'Modernia Second Affection',
  'Moran',
  'Mustang',
  'N102',
  'Naga',
  'Neon',
  'Neon Bling Bullet',
  'Neon: Blue Ocean',
  'Nero',
  'Neve',
  'Neverland',
  'New Year New Sword',
  'Nihilister',
  'Noah',
  'No Caller ID',
  'Noir',
  'Noir Black Rabbit',
  'Noise',
  'Noise Cherry Blossom Stage',
  'Noise Classic Diva',
  'Novel',
  'Novel Detective Nurse',
  'Novel Penguin Holmes',
  'Nya Nya Paradise',
  'One More Time',
  'Outer Automata',
  'Oswald',
  'Papillon',
  'Pascal',
  'Pepper',
  'Pepper Ocean Vitamin',
  'Perfect Maid',
  'Pinne',
  'Poli',
  'Poli Sweet Holic',
  'Poli Cheer Up Police',
  'Power',
  'Privaty',
  'Privaty Banquet Princess',
  'Privaty Government Grunt',
  'Privaty: Unkind Maid',
  'Product 08',
  'Product 12',
  'Product 12: B-0006',
  'Product 12: C-1002',
  'Product 12: 6000-D',
  'Product 23',
  'Queen\'s Order',
  'Quency',
  'Quiry',
  'Rapi',
  'Rapi_old',
  'Rapi White Promise',
  'Rapi Classic Vacation',
  'Raptillion',
  'Rapunzel',
  'Raven',
  'Re: Cipe For You',
  'RED ASH 1',
  'RED ASH 2',
  'Red Hood',
  'Rei',
  'Rem',
  'Rem Handy Maid',
  'Rem Pure Blossom',
  'Ram',
  'Emilia',
  'Emilia Clumsy Maid',
  'Emilia Spring Breeze',
  'Rian',
  'Rosanna',
  'Rosanna Ms. Dangerous',
  'Rosanna: Chic Ocean',
  'Rouge',
  'Rose',
  'Rumani',
  'Rupee',
  'Rupee Rabbit Deluxe',
  'Rupee: Winter Shopper',
  'Ruru',
  'Sakura',
  'Sakura Midnight Stealth',
  'Sakura: Bloom in Summer',
  'Scarlet',
  'Scarlet: Black Shadow',
  'School Of Lock',
  'Sea You Again',
  'Shifty',
  'Shifty_old',
  'Signal',
  'Signal Dramatic Chocolate',
  'Sin',
  'Snow White',
  'Snow White White Knight',
  'Snow White: Innocent Days',
  'Soda',
  'Soda: Twinkling Bunny',
  'Soldier EG',
  'Soldier FA',
  'Soldier OW',
  'Soline',
  'Sugar',
  'Sugar Hard-Boiled',
  'Sugar Wild Backyard',
  'Syuen',
  'Tia',
  'Timi',
  'Tove',
  'Trony',
  'T.Rony',
  'T.A.L.O.S (Kilo)',
  'Unknown',
  'Vesti',
  'Volume',
  'Viper',
  'Viper Toxic Rabbit',
  'Viper Shine of Love',
  'Yan',
  'Yan Sunrise Market',
  'Yin',
  'Yulha',
  'Yuni',
  'Yuni Pretty In Pink',
  'White Memory 1',
  'White Memory 2',
  'Zwei',
  'Smol Ade',
  'Smol Anchor',
  'Smol Bolt',
  'Smol Frima',
  'Smol Helm',
  'Smol Liter',
  'Smol Mary',
  'Smol Mast',
  'Smol Pepper',
  'Smol Maid Privaty',
  'Smol Rapi',
  'Smol Yan',
  'Smol Rem',
  'Smol Ram',
  'Smol Emilia',
  'Story 00-01',
  'Story 00-01 no filter',
  'Story 00-02',
  'Story 00-02 no filter',
  'Story 00-03',
  'Story 02-01',
  'Story 04-01',
  'Story 04-02',
  'Story 04-05',
  'Story 07-02',
  'Story 12-01',
  'Story 13-02',
  'Story 13-03',
  'Story 14-01',
  'Story 14-03',
  'Story 14-05',
  'Story 15-01',
  'Story 19-01',
  'Story 20-01',
  'Story 21-01',
  'Story 22-01',
  'Story 22-02',
  'Story 22-06',
  'Story 25-01',
  'Story 26-02'
]
