export const animationMappings: Record<string, string[]> = {
  happy: ['delight', 'joy', 'smile', 'laugh', 'excited', 'glee', 'grin', 'chuckle', 'giggle', 'smirk', 'beam', 'radiant', 'happy', 'content', 'pleased', 'amused', 'cheerful', 'triumph', 'warmth', 'bright', 'lighthearted'],
  cry: ['cry', 'crying', 'weep', 'tears', 'sobbing', 'wail'],
  sad: [
    // High intensity (sad) - actual sadness/very sad/almost crying
    'depressed',
    'sorrow',
    'tear',
    'gloom',
    'worry',
    'sobbing',
    'devastated',
    'heartbroken',
    'hurt',
    'pain',
    'agony',
    'grief',
    'mourn',
    'sad',
    'unhappy',
    'melancholy',
    'despair',
    'hopeless',
    'anguish',
    'misery',
    'falter',
    'tremble',
    'shaky',
    'crumbling',
    'broken',
    // Low intensity (sad_02) - about to cry, watery eyes
    'teary',
    'upset',
    'emotional',
    'misty',
    'choked up',
    'pout',
    'whine',
  ],
  angry: [
    // High intensity (angry_02)
    'furious',
    'rage',
    'shouting',
    'yelling',
    'livid',
    'outraged',
    'irate',
    'mad',
    'fury',
    'anger',
    'seethe',
    'hiss',
    'growl',
    'snap',
    'bitter',
    'resent',
    'hate',
    'loathe',
    'vengeful',
    'grate',
    // Low intensity (angry_03)
    'stern',
    'frown',
    'serious',
    'disapproving',
    'scowl',
    'glare',
    'cross',
    'cold',
    'sharp',
    'dismissive',
    'commanding',
    // Medium intensity (angry)
    'annoyed',
    'irritated',
    'bothered',
    'grumpy',
    'frustrated',
    'groan',
    'disgust',
    'clench',
    'flinch',
    'recoil'
  ],
  surprise: ['shock', 'surprised', 'startle', 'gasp', 'wide-eyed', 'blink', 'stunned', 'amazed', 'astonished', 'aback', 'confused', 'puzzled', 'catch', 'widen', 'breath catches'],
  shy: ['blush', 'embarrassed', 'shy', 'bashful', 'timid', 'stutter', 'stammer', 'fluster', 'nervous', 'anxious', 'cautious', 'hesitant', 'uncertain', 'apologize', 'forgive me'],
  no: ['frowning', 'disapproval', 'skeptical', 'indifferent', 'unimpressed', 'shake head', 'deny', 'refuse', 'reject', 'doubt', 'sigh', 'turn away'],
  idle: ['stand', 'wait', 'default', 'calm', 'neutral']
}
